language: r
cache: packages
dist: bionic

r:
  - devel
  - release

addons:
  apt:
    packages:
      - python3.8
      - python3-setuptools
      - python3-pip
      - r-bioc-s4vectors
      - r-cran-testthat
      - r-cran-reticulate

script:
  - pip3 install --upgrade pip
  - pip3 install --upgrade -r python_requirements.txt --no-cache-dir
  - R CMD build .
  - R CMD check *tar.gz
