language: r
os: linux
dist: focal
jobs:
  include:
    - name: amd64_r_release
      arch: amd64
      r: release
    - name: amd64_r_devel
      arch: amd64
      r: devel
addons:
  apt:
    packages:
      - python3
      - python3-setuptools
      - python3-pip
r_packages:
  - testthat
  - reticulate
  - S4Vectors
  - methods
install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade -r python_requirements.txt --no-cache-dir
script:
  - R CMD build .
  - R CMD check *tar.gz
