language: r
cache: packages
dist: bionic

r:
  - devel
  - release

addons:
  apt:
    packages:
      - python3.8
      - python3-setuptools
      - python3-pip

r_binary_packages:
  - testthat
  - reticulate
  - S4Vectors
  - methods

script:
  - pip3 install --upgrade pip
  - pip3 install --upgrade -r python_requirements.txt --no-cache-dir
  - R CMD build .
  - R CMD check *tar.gz
