language: r
os: linux
dist: bionic
jobs:
  include:
    - name: amd64_r3.6
      arch: amd64
      r: 3.6
      python: 3.7
    - name: amd64_r4.0
      arch: amd64
      r: 4.0
      python: 3.7
addons:
  apt:
    packages:
      - python3-setuptools
      - python3-pip
r_packages:
  - testthat
  - reticulate
  - S4Vectors
  - methods
install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade -r python_requirements.txt --no-cache-dir
script:
  - R CMD build .
  - R CMD check *tar.gz
